title: Llewellyn Adonteng Paintsil
author: llewellyn Adonteng Paintsil
email: llewellynPaintsil34@gmail.com
facebook_username: Llewellyn Paintsil
github_username: Llewellyn500
twitter_username: LlewellynAdont1
youtube_username: c/LPTeach
linkedin_username: Llewellyn Paintsil
instagram_username: llewellynpaintsil
theme: jekyll-theme-merlot
