title: Llewellyn Adonteng Paintsil

author: llewellyn Adonteng Paintsil


  email: llewellynPaintsil34@gmail.com
  facebook_username: Llewellyn Paintsil
  github_username: Llewellyn500
  twitter_username: LlewellynAdont1
  youtube_username: c/LPTeach
  linkedin_username: Llewellyn Paintsil
  instagram_username: llewellynpaintsil

rss-description: This website is a virtual proof that I'm awesome

theme: jekyll-theme-merlot
